services:
  psql_bp:
    container_name: database_stock
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      TZ: "Asia/Bangkok"
      PGDATA: /var/lib/postgresql/18/main
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - blueprint
  migrate:
    image: migrate/migrate:v4.19.0
    container_name: migrate
    entrypoint: ""
    volumes:
      - ./import/migrations:/migrations
    command: >
      sh -c "migrate -path /migrations -database 'postgres://postgres:1234@psql_bp:5432/stock_db?sslmode=disable' up"
    depends_on:
      psql_bp:
        condition: service_healthy
    networks:
      - blueprint

  api:
    container_name: api_stock
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:1234@psql_bp:5432/stock_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      psql_bp:
        condition: service_healthy
    networks:
      - blueprint

volumes:
  psql_volume:
networks:
  blueprint:
